### ISSUE TITLE
Print in the same line with different aligns

### ISSUE THREAD

**Issue by ital0** [ingoncalves/escpos-xml#7]
Hello!
I'm trying to print in the same line but with different alignments, doing like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<document>
  <line-feed />
  <align mode="left">
    <bold>
      <text size="2:1">TEXT ON LEFT</text>
    </bold>
  </align>
  <align mode="right">
    <bold>
      <text size="1:0">TEXT ON RIGHT</text>
    </bold>
  </align>
</document>
```

If I do this using `<text-line>` instead of `<text>` it works, but, obviously, the printer jumps one line.

Is it possible?

Thanks in advance.

**Comment by ingoncalves** [comment]
The alignment tag `<align>`, only applies to `<text-line>`, `<barcode>` and others block tags, but not to `<text>` tag. The protocol defined it.
For alignment in `<text>`, you may add white-spaces as you want, such as `<text>      Hello</text>`. However, I'm not sure if it works. I think that you must use `&#160;` or `\u0020` instead of plain white-space, such as `<text>&#160;&#160;&#160;&#160;&#160;&#160;Hello</text>`. You may try it.
